# Generated by Django 5.2.6 on 2026-03-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0003_alter_realestatecomplexbuilding_real_estate_complex'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Region',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('is_active', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                        ('name', models.CharField(max_length=100, unique=True, verbose_name='Регион')),
                        ('code', models.CharField(max_length=10, unique=True, verbose_name='Код региона')),
                    ],
                    options={
                        'verbose_name': 'Регион',
                        'verbose_name_plural': 'Регионы',
                        'db_table': 'region',
                        'ordering': ['name'],
                    },
                ),
                migrations.CreateModel(
                    name='City',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('is_active', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                        ('name', models.CharField(max_length=100, verbose_name='Город')),
                        ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.region', verbose_name='Регион')),
                    ],
                    options={
                        'verbose_name': 'Город',
                        'verbose_name_plural': 'Города',
                        'db_table': 'city',
                        'ordering': ['name'],
                        'unique_together': {('name', 'region')},
                    },
                ),
                migrations.CreateModel(
                    name='District',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('is_active', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                        ('name', models.CharField(max_length=100, verbose_name='Район')),
                        ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.city', verbose_name='Город')),
                    ],
                    options={
                        'verbose_name': 'Район',
                        'verbose_name_plural': 'Районы',
                        'db_table': 'district',
                        'ordering': ['name'],
                        'unique_together': {('name', 'city')},
                    },
                ),
            ],
        ),
    ]
