# Generated by Django 6.0.4 on 2026-04-28 20:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('station', models.CharField(max_length=100, verbose_name='Станция')),
                ('line', models.CharField(max_length=100, verbose_name='Линия')),
                ('line_color', models.CharField(help_text='Код цвета линии в формате #RRGGBB.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Введите цвет в формате #RRGGBB.')], verbose_name='Цвет линии (RGB)')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Метро',
                'verbose_name_plural': 'Метро',
                'db_table': 'metro',
                'ordering': ['city__name', 'line', 'station'],
                'abstract': False,
                'unique_together': {('station', 'line', 'city')},
            },
        ),
    ]
