# Generated by Django 6.0.4 on 2026-06-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_metroline_migrate_metro'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='metro',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='metroline',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(
                fields=('name', 'region'),
                name='unique_city_name_region',
            ),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(
                fields=('name', 'city'),
                name='unique_district_name_city',
            ),
        ),
        migrations.AddConstraint(
            model_name='metro',
            constraint=models.UniqueConstraint(
                fields=('station', 'metro_line'),
                name='unique_metro_station_line',
            ),
        ),
        migrations.AddConstraint(
            model_name='metroline',
            constraint=models.UniqueConstraint(
                fields=('line', 'city'),
                name='unique_metro_line_line_city',
            ),
        ),
    ]
