# Generated by Django 5.2.6 on 2026-03-12 20:20

import django.utils.timezone
from django.db import migrations, models

import users.managers


class Migration(migrations.Migration):
    """Описание класса Migration.

    Инкапсулирует данные и поведение, необходимые для работы компонента
    в данном модуле.
    """

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'password',
                    models.CharField(max_length=128, verbose_name='password'),
                ),
                (
                    'last_login',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='last login'
                    ),
                ),
                (
                    'is_superuser',
                    models.BooleanField(
                        default=False,
                        help_text=(
                            'Designates that this user has all permissions '
                            'without explicitly assigning them.'
                        ),
                        verbose_name='superuser status',
                    ),
                ),
                (
                    'is_staff',
                    models.BooleanField(
                        default=False,
                        help_text=(
                            'Designates whether the user can log into this '
                            'admin site.'
                        ),
                        verbose_name='staff status',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text=(
                            'Designates whether this user should be treated '
                            'as active. Unselect this instead of deleting '
                            'accounts.'
                        ),
                        verbose_name='active',
                    ),
                ),
                (
                    'date_joined',
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name='date joined',
                    ),
                ),
                (
                    'first_name',
                    models.CharField(
                        max_length=150, verbose_name='First name'
                    ),
                ),
                (
                    'last_name',
                    models.CharField(max_length=150, verbose_name='Last name'),
                ),
                (
                    'email',
                    models.EmailField(
                        max_length=254, unique=True, verbose_name='Email'
                    ),
                ),
                (
                    'phone_number',
                    models.CharField(
                        max_length=20, unique=True, verbose_name='Phone number'
                    ),
                ),
                (
                    'is_real_estate_agent',
                    models.BooleanField(
                        default=False, verbose_name='Real estate agent'
                    ),
                ),
                (
                    'agency_name',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Agency name'
                    ),
                ),
                (
                    'groups',
                    models.ManyToManyField(
                        blank=True,
                        help_text=(
                            'The groups this user belongs to. '
                            'A user will get all permissions granted '
                            'to each of their groups.'
                        ),
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.group',
                        verbose_name='groups',
                    ),
                ),
                (
                    'user_permissions',
                    models.ManyToManyField(
                        blank=True,
                        help_text='Specific permissions for this user.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.permission',
                        verbose_name='user permissions',
                    ),
                ),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
    ]
