# Generated by Django 5.2.6 on 2025-09-15 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrenchMortgageCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_property_cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Итоговая стоимость объекта, руб.')),
                ('initial_payment_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Первоначальный взнос, %')),
                ('initial_payment_date', models.DateField(verbose_name='Дата первоначального взноса')),
                ('mortgage_term', models.IntegerField(verbose_name='Срок кредита, лет')),
                ('trench_count', models.IntegerField(verbose_name='Количество траншей')),
                ('total_loan_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма кредита, руб.')),
                ('total_overpayment', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма переплат, руб.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property', verbose_name='Объект')),
            ],
        ),
        migrations.CreateModel(
            name='Trench',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trench_number', models.IntegerField(verbose_name='Номер транша')),
                ('trench_date', models.DateField(verbose_name='Дата транша')),
                ('trench_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Сумма транша, %')),
                ('trench_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма транша, руб.')),
                ('annual_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Годовая ставка, %')),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Ежемесячный платеж, руб.')),
                ('payments_count', models.IntegerField(verbose_name='Число платежей')),
                ('remaining_debt', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Остаток долга, руб.')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trenches', to='trench_mortgage.trenchmortgagecalculation')),
            ],
            options={
                'ordering': ['trench_number'],
            },
        ),
    ]
