# Generated by Django 6.0.4 on 2026-06-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trench_mortgage', '0002_align_calculation_with_mortgage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trenchmortgagecalculation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
