# Generated by Django 6.0.4 on 2026-06-16 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trench_mortgage', '0003_alter_trenchmortgagecalculation_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trenchmortgagecalculation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trench_mortgage_calculations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
