# Generated by Django 6.0.4 on 2026-06-17 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trench_mortgage', '0004_trenchmortgagecalculation_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trench',
            options={'ordering': ['trench_number'], 'verbose_name': 'Транш', 'verbose_name_plural': 'Транши'},
        ),
        migrations.AlterModelOptions(
            name='trenchmortgagecalculation',
            options={'verbose_name': 'Расчет траншевой ипотеки', 'verbose_name_plural': 'Расчеты траншевой ипотеки'},
        ),
        migrations.AlterField(
            model_name='trench',
            name='calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trenches', to='trench_mortgage.trenchmortgagecalculation', verbose_name='Расчет траншевой ипотеки'),
        ),
        migrations.AlterField(
            model_name='trenchmortgagecalculation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата расчета'),
        ),
    ]
