# Generated by Django 5.2.6 on 2026-03-14 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('property', '0004_move_location_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('initial_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Первый взнос, руб.')),
                ('max_monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Максимальный ежемесячный платёж, руб.')),
                ('preferential_programs', models.TextField(blank=True, verbose_name='Доступность льготных программ')),
                ('has_owned_property', models.BooleanField(blank=True, choices=[(True, 'Да'), (False, 'Нет')], null=True, verbose_name='Наличие недвижимости в собственности')),
                ('purchase_goal', models.CharField(blank=True, choices=[('living', 'Для жизни'), ('investment', 'Для инвестиций')], max_length=20, verbose_name='Цель покупки')),
                ('area_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь квартиры от, м2')),
                ('area_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь квартиры до, м2')),
                ('desired_floor', models.CharField(blank=True, max_length=100, verbose_name='Этаж')),
                ('cardinal_directions', models.CharField(blank=True, max_length=255, verbose_name='Стороны света')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('desired_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desired_city_customers', to='location.city', verbose_name='Желаемый город покупки')),
                ('desired_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desired_district_customers', to='location.district', verbose_name='Желаемый район покупки')),
                ('desired_layouts', models.ManyToManyField(blank=True, related_name='customers', to='property.apartmentlayout', verbose_name='Планировка')),
                ('residence_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residence_customers', to='location.city', verbose_name='Город проживания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'customer',
                'ordering': ['-created_at', 'first_name', 'last_name'],
                'abstract': False,
            },
        ),
    ]
