# Generated by Django 5.2.6 on 2026-03-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_keyrate'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='preferential_programs',
        ),
        migrations.AddField(
            model_name='customer',
            name='preferential_programs',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_preferential': True}, related_name='customers_with_preferential_access', to='bank.mortgageprogram', verbose_name='Доступные льготные программы'),
        ),
    ]
