# Generated by Django 5.2.6 on 2026-04-27 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customer', '0002_remove_customer_preferential_programs_and_more'),
        ('mortgage', '0002_mortgagecalculation_base_property_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCalculation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата сохранения'
                    ),
                ),
                (
                    'calculation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='customer_links',
                        to='mortgage.mortgagecalculation',
                        verbose_name='Расчет',
                    ),
                ),
                (
                    'customer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='calculation_links',
                        to='customer.customer',
                        verbose_name='Клиент',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Расчет клиента',
                'verbose_name_plural': 'Расчеты клиентов',
                'db_table': 'customer_calculation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='saved_calculations',
            field=models.ManyToManyField(
                blank=True,
                related_name='saved_for_customers',
                through='customer.CustomerCalculation',
                to='mortgage.mortgagecalculation',
                verbose_name='Сохраненные расчеты',
            ),
        ),
        migrations.AddConstraint(
            model_name='customercalculation',
            constraint=models.UniqueConstraint(
                fields=('customer', 'calculation'),
                name='unique_customer_calculation',
            ),
        ),
    ]
