# Generated by Django 6.0.4 on 2026-06-17 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_created_at_alter_customer_is_active'),
        ('trench_mortgage', '0005_alter_trench_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTrenchCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата сохранения')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_links', to='trench_mortgage.trenchmortgagecalculation', verbose_name='Расчет')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trench_calculation_links', to='customer.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Траншевый расчет клиента',
                'verbose_name_plural': 'Траншевые расчеты клиентов',
                'db_table': 'customer_trench_calculation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='saved_trench_calculations',
            field=models.ManyToManyField(blank=True, related_name='saved_for_customers', through='customer.CustomerTrenchCalculation', to='trench_mortgage.trenchmortgagecalculation', verbose_name='Сохраненные траншевые расчеты'),
        ),
        migrations.AddConstraint(
            model_name='customertrenchcalculation',
            constraint=models.UniqueConstraint(fields=('customer', 'calculation'), name='unique_customer_trench_calculation'),
        ),
    ]
