# Generated by Django 6.0.4 on 2026-06-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_keyrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgageprogram',
            name='preferential_program_type',
            field=models.CharField(blank=True, choices=[('', 'Не указан'), ('information_technology', 'IT-ипотека'), ('family', 'Семейная ипотека')], max_length=32, verbose_name='Тип льготной программы'),
        ),
    ]
