# Generated by Django 6.0.4 on 2026-06-10 07:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add bank-specific mortgage program conditions."""

    dependencies = [
        ('bank', '0004_remove_mortgageprogram_preferential_program_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankprogram',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Процентная ставка, %'),
        ),
        migrations.AddField(
            model_name='bankprogram',
            name='minimum_initial_payment_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Минимальный первый взнос, %'),
        ),
    ]
