# Generated by Django 6.0.4 on 2026-06-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add bank logo URL for catalog rendering and parser updates."""

    dependencies = [
        ('bank', '0005_bankprogram_interest_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='logo_url',
            field=models.URLField(blank=True, default='', verbose_name='Логотип'),
        ),
    ]
