# Generated by Django 6.0.4 on 2026-06-10 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """Adds maximum mortgage loan term fields for banks and bank programs."""

    dependencies = [
        ('bank', '0006_bank_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='maximum_loan_term_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальный срок кредита, лет'),
        ),
        migrations.AddField(
            model_name='bankprogram',
            name='maximum_loan_term_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальный срок кредита, лет'),
        ),
    ]
