# Generated by Django 6.0.4 on 2026-06-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    """Expands stored bank logo URL length for CDN links."""

    dependencies = [
        ('bank', '0007_bank_maximum_loan_term_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='logo_url',
            field=models.URLField(blank=True, default='', max_length=1000, verbose_name='Логотип'),
        ),
    ]
