# Generated by Django 6.0.4 on 2026-06-10 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Cascades bank program links when deleting a bank."""

    dependencies = [
        ('bank', '0008_alter_bank_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankprogram',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bank', verbose_name='Банк'),
        ),
    ]
