# Generated by Django 6.0.4 on 2026-06-10 14:37

from django.db import migrations


class Migration(migrations.Migration):
    """Removes mortgage condition fields from banks."""

    dependencies = [
        ('bank', '0009_alter_bankprogram_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='maximum_loan_term_years',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='salary_client_discount',
        ),
    ]
