# Generated by Django 6.0.4 on 2026-06-11 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_remove_bank_interest_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageProgramAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('source_name', models.CharField(max_length=255, verbose_name='Написание из источника')),
                ('normalized_name', models.CharField(editable=False, max_length=255, unique=True, verbose_name='Ключ сопоставления')),
                ('source', models.CharField(blank=True, default='', max_length=255, verbose_name='Источник')),
                ('mortgage_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='bank.mortgageprogram', verbose_name='Эталонная ипотечная программа')),
            ],
            options={
                'verbose_name': 'Алиас ипотечной программы',
                'verbose_name_plural': 'Алиасы ипотечных программ',
                'db_table': 'mortgage_program_alias',
                'ordering': ['mortgage_program__name', 'source_name'],
                'abstract': False,
            },
        ),
    ]
