# Generated by Django 6.0.4 on 2026-06-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_mortgageprogramalias'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankprogram',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='bankprogram',
            constraint=models.UniqueConstraint(
                fields=('bank', 'mortgage_program'),
                name='unique_bank_program_pair',
            ),
        ),
    ]
