# Generated by Django 6.0.4 on 2026-06-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_alter_bankprogram_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='bankprogram',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='bankprogram',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='keyrate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='keyrate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='mortgageprogram',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='mortgageprogram',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='mortgageprogramalias',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='mortgageprogramalias',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='mortgageprogramregionalcreditlimit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='mortgageprogramregionalcreditlimit',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно'),
        ),
    ]
