# Generated by Django 6.0.4 on 2026-07-13 13:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_alter_bank_created_at_alter_bank_is_active_and_more'),
        ('property', '0014_developerregion_developer_regions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperMortgageProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('price_increase_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Удорожание, %')),
                ('grace_period_months', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Срок льготного периода, мес.')),
                ('grace_period_interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Ставка на льготный период, % годовых')),
                ('minimum_initial_payment_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Первоначальный взнос, %')),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Годовая ставка, %')),
                ('maximum_loan_term_years', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальный срок кредита, лет')),
                ('maximum_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Максимальная сумма кредита')),
                ('rate_discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Дисконт к ставке, п. п.')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='developer_mortgage_programs', to='bank.bank', verbose_name='Банк')),
                ('company_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='developer_mortgage_programs', to='property.companygroup', verbose_name='Группа компаний')),
                ('mortgage_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='developer_mortgage_programs', to='bank.mortgageprogram', verbose_name='Ипотечная программа')),
                ('real_estate_complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='developer_mortgage_programs', to='property.realestatecomplex', verbose_name='ЖК')),
            ],
            options={
                'verbose_name': 'Ипотечная программа застройщика',
                'verbose_name_plural': 'Ипотечные программы застройщиков',
                'db_table': 'developer_mortgage_program',
                'ordering': ['company_group__name', 'real_estate_complex__name', 'bank__name', 'mortgage_program__name'],
                'abstract': False,
                'indexes': [models.Index(fields=['company_group', 'bank', 'mortgage_program'], name='dev_mort_group_bank_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('grace_period_months__isnull', True), ('grace_period_months__gte', 1), _connector='OR'), name='dev_mort_grace_months_positive'), models.CheckConstraint(condition=models.Q(('grace_period_interest_rate__isnull', True), models.Q(('grace_period_interest_rate__gte', Decimal('0')), ('grace_period_interest_rate__lte', Decimal('100'))), _connector='OR'), name='dev_mort_grace_rate_range'), models.CheckConstraint(condition=models.Q(('minimum_initial_payment_percent__isnull', True), models.Q(('minimum_initial_payment_percent__gte', Decimal('0')), ('minimum_initial_payment_percent__lte', Decimal('100'))), _connector='OR'), name='dev_mort_initial_payment_range'), models.CheckConstraint(condition=models.Q(('interest_rate__isnull', True), models.Q(('interest_rate__gte', Decimal('0')), ('interest_rate__lte', Decimal('100'))), _connector='OR'), name='dev_mort_interest_rate_range'), models.CheckConstraint(condition=models.Q(('rate_discount_percent__isnull', True), models.Q(('rate_discount_percent__gte', Decimal('0')), ('rate_discount_percent__lte', Decimal('100'))), _connector='OR'), name='dev_mort_discount_range'), models.CheckConstraint(condition=models.Q(('maximum_loan_term_years__isnull', True), ('maximum_loan_term_years__gte', 1), _connector='OR'), name='dev_mort_max_term_positive'), models.CheckConstraint(condition=models.Q(('maximum_loan_amount__isnull', True), ('maximum_loan_amount__gte', Decimal('0')), _connector='OR'), name='dev_mort_max_amount_nonnegative')],
            },
        ),
    ]
