# Generated by Django 6.0.4 on 2026-07-13 17:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_developermortgageprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='developermortgageprogram',
            name='source_key',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True, verbose_name='Ключ записи источника'),
        ),
        migrations.AddField(
            model_name='developermortgageprogram',
            name='source_program_column',
            field=models.CharField(blank=True, default='', editable=False, max_length=1, verbose_name='Столбец программы источника'),
        ),
        migrations.AddField(
            model_name='developermortgageprogram',
            name='source_program_variant_index',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='Номер варианта программы источника'),
        ),
        migrations.AddField(
            model_name='developermortgageprogram',
            name='source_record_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True, verbose_name='ID записи источника'),
        ),
        migrations.AddField(
            model_name='developermortgageprogram',
            name='source_sheet_row',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True, verbose_name='Строка исходной таблицы'),
        ),
        migrations.AlterField(
            model_name='developermortgageprogram',
            name='price_increase_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=6, null=True, verbose_name='Удорожание, %'),
        ),
    ]
