# Generated by Django 4.2.7 on 2025-08-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('property_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('initial_payment_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('initial_payment_date', models.DateField()),
                ('mortgage_term', models.IntegerField()),
                ('annual_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('has_grace_period', models.BooleanField()),
                ('grace_period_term', models.IntegerField(blank=True, null=True)),
                ('grace_period_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grace_payments_count', models.IntegerField(blank=True, null=True)),
                ('grace_period_end_date', models.DateField(blank=True, null=True)),
                ('grace_monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('loan_after_grace', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('main_payments_count', models.IntegerField(blank=True, null=True)),
                ('mortgage_end_date', models.DateField(blank=True, null=True)),
                ('main_monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_overpayment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
    ]
