# Generated by Django 5.2.6 on 2025-09-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.CharField(max_length=255, verbose_name='Застройщик')),
                ('city', models.CharField(choices=[('Москва', 'Москва'), ('Санкт-Петербург', 'Санкт-Петербург'), ('Калининград', 'Калининград')], max_length=50, verbose_name='Город')),
                ('complex_name', models.CharField(max_length=255, verbose_name='Название ЖК')),
                ('complex_class', models.CharField(choices=[('Комфорт', 'Комфорт'), ('Комфорт+', 'Комфорт+'), ('Бизнес', 'Бизнес'), ('Элит', 'Элит')], max_length=50, verbose_name='Класс ЖК')),
                ('building', models.CharField(max_length=50, verbose_name='Корпус')),
                ('apartment_number', models.CharField(max_length=50, verbose_name='№ квартиры')),
                ('layout', models.CharField(max_length=255, verbose_name='Планировка')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('property_cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость объекта, руб.')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
                'ordering': ['-created_at'],
            },
        ),
    ]
