# Generated by Django 5.2.6 on 2026-03-06 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_apartmentdecoration_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestatecomplexbuilding',
            name='real_estate_complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.realestatecomplex', verbose_name='ЖК'),
        ),
    ]
