# Generated by Django 5.2.6 on 2026-03-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Описание класса Migration.

    Инкапсулирует данные и поведение, необходимые для работы компонента
    в данном модуле.
    """

    dependencies = [
        ('location', '0001_initial'),
        (
            'property',
            '0003_alter_realestatecomplexbuilding_real_estate_complex',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='realestatecomplex',
                    name='district',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='location.district',
                        verbose_name='Район',
                    ),
                ),
                migrations.DeleteModel(
                    name='District',
                ),
                migrations.DeleteModel(
                    name='City',
                ),
                migrations.DeleteModel(
                    name='Region',
                ),
            ],
        ),
    ]
