# Generated by Django 6.0.4 on 2026-04-28 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_metroline_migrate_metro'),
        ('property', '0004_move_location_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateComplexMetroAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('walking_time_minutes', models.PositiveSmallIntegerField(verbose_name='Время до метро, мин. пешком')),
                ('metro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.metro', verbose_name='Станция метро')),
                ('real_estate_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metro_availability', to='property.realestatecomplex', verbose_name='ЖК')),
            ],
            options={
                'verbose_name': 'Доступность метро ЖК',
                'verbose_name_plural': 'Доступность метро ЖК',
                'db_table': 'real_estate_complex_metro_availability',
                'ordering': ['walking_time_minutes', 'metro__station'],
                'abstract': False,
                'unique_together': {('real_estate_complex', 'metro')},
            },
        ),
    ]
