# Generated by Django 6.0.4 on 2026-05-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_realestatecomplexmetroavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatecomplexbuilding',
            name='commissioning_quarter',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'I кв.'), (2, 'II кв.'), (3, 'III кв.'), (4, 'IV кв.')], null=True, verbose_name='Квартал ввода в эксплуатацию'),
        ),
        migrations.AddField(
            model_name='realestatecomplexbuilding',
            name='commissioning_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год ввода в эксплуатацию'),
        ),
        migrations.AddField(
            model_name='realestatecomplexbuilding',
            name='key_handover_quarter',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'I кв.'), (2, 'II кв.'), (3, 'III кв.'), (4, 'IV кв.')], null=True, verbose_name='Квартал выдачи ключей'),
        ),
        migrations.AddField(
            model_name='realestatecomplexbuilding',
            name='key_handover_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год выдачи ключей'),
        ),
        migrations.AlterField(
            model_name='realestatecomplexbuilding',
            name='commissioning_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата ввода в эксплуатацию'),
        ),
        migrations.AlterField(
            model_name='realestatecomplexbuilding',
            name='key_handover_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи ключей'),
        ),
    ]
