# Generated by Django 6.0.4 on 2026-05-19 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_realestatecomplexbuilding_commissioning_quarter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Вид из окна')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид из окна',
                'verbose_name_plural': 'Виды из окна',
                'db_table': 'window_view',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='property',
            name='floor_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='property/floor_plans/', verbose_name='План этажа'),
        ),
        migrations.AddField(
            model_name='property',
            name='layout_image',
            field=models.ImageField(blank=True, null=True, upload_to='property/layouts/', verbose_name='Планировка'),
        ),
        migrations.AddField(
            model_name='property',
            name='window_view_image',
            field=models.ImageField(blank=True, null=True, upload_to='property/window_views/', verbose_name='Вид из окна'),
        ),
        migrations.CreateModel(
            name='PropertyWindowView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property', verbose_name='Объект недвижимости')),
                ('window_view', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='property.windowview', verbose_name='Вид из окна')),
            ],
            options={
                'verbose_name': 'Вид из окна объекта недвижимости',
                'verbose_name_plural': 'Виды из окна объектов недвижимости',
                'db_table': 'property_window_view',
                'ordering': ['property', 'window_view__name'],
                'abstract': False,
                'unique_together': {('property', 'window_view')},
            },
        ),
        migrations.AddField(
            model_name='property',
            name='window_views',
            field=models.ManyToManyField(blank=True, related_name='properties', through='property.PropertyWindowView', to='property.windowview', verbose_name='Виды из окна'),
        ),
    ]
