# Generated by Django 6.0.4 on 2026-06-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_windowview_property_floor_plan_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatecomplex',
            name='investment_potential',
            field=models.TextField(blank=True, null=True, verbose_name='Инвестиционный потенциал'),
        ),
        migrations.AddField(
            model_name='realestatecomplex',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='property/complexes/', verbose_name='Фото ЖК'),
        ),
    ]
