# Generated by Codex on 2026-06-11

import django.db.models.deletion
from django.db import migrations, models


TRANSPORT_ACCESSIBILITY_TYPES = (
    'Пешком',
    'На транспорте',
    'На электричке',
)


def create_transport_accessibility_types(apps, schema_editor):
    """Create initial transport accessibility type dictionary records."""
    TransportAccessibilityType = apps.get_model(
        'property', 'TransportAccessibilityType'
    )

    for name in TRANSPORT_ACCESSIBILITY_TYPES:
        TransportAccessibilityType.objects.get_or_create(name=name)


def fill_existing_metro_availability(apps, schema_editor):
    """Fill existing metro availability rows with walking accessibility."""
    TransportAccessibilityType = apps.get_model(
        'property', 'TransportAccessibilityType'
    )
    RealEstateComplexMetroAvailability = apps.get_model(
        'property', 'RealEstateComplexMetroAvailability'
    )

    walking_type, _ = TransportAccessibilityType.objects.get_or_create(
        name='Пешком'
    )
    RealEstateComplexMetroAvailability.objects.filter(
        transport_accessibility_type__isnull=True
    ).update(transport_accessibility_type_id=walking_type.pk)


class Migration(migrations.Migration):
    """Add transport accessibility types for metro availability."""

    dependencies = [
        ('property', '0008_realestatecomplex_investment_potential_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportAccessibilityType',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Снимите галочку, чтобы скрыть запись.',
                        verbose_name='Активно',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='Дата создания',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name='Дата изменения',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name='Тип транспортной доступности',
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name='Описание',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Тип транспортной доступности',
                'verbose_name_plural': 'Типы транспортной доступности',
                'db_table': 'transport_accessibility_type',
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(
            create_transport_accessibility_types,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='realestatecomplexmetroavailability',
            name='transport_accessibility_type',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='property.transportaccessibilitytype',
                verbose_name='Способ',
            ),
        ),
        migrations.RunPython(
            fill_existing_metro_availability,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='realestatecomplexmetroavailability',
            name='transport_accessibility_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='property.transportaccessibilitytype',
                verbose_name='Способ',
            ),
        ),
        migrations.AlterField(
            model_name='realestatecomplexmetroavailability',
            name='walking_time_minutes',
            field=models.PositiveSmallIntegerField(
                verbose_name='Время, мин',
            ),
        ),
    ]
