# Generated by Django 6.0.4 on 2026-06-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_city_unique_together_and_more'),
        ('property', '0009_transport_accessibility_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='propertywindowview',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='realestatecomplex',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='realestatecomplexbuilding',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='realestatecomplexmetroavailability',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='propertywindowview',
            constraint=models.UniqueConstraint(
                fields=('property', 'window_view'),
                name='unique_property_window_view',
            ),
        ),
        migrations.AddConstraint(
            model_name='realestatecomplex',
            constraint=models.UniqueConstraint(
                fields=('name', 'developer'),
                name='unique_complex_name_developer',
            ),
        ),
        migrations.AddConstraint(
            model_name='realestatecomplexbuilding',
            constraint=models.UniqueConstraint(
                fields=('number', 'real_estate_complex'),
                name='unique_complex_building_number',
            ),
        ),
        migrations.AddConstraint(
            model_name='realestatecomplexmetroavailability',
            constraint=models.UniqueConstraint(
                fields=('real_estate_complex', 'metro'),
                name='unique_complex_metro_station',
            ),
        ),
    ]
