# Generated by Django 6.0.4 on 2026-06-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_propertywindowview_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentdecoration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='apartmentdecoration',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='apartmentlayout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='apartmentlayout',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='propertywindowview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='propertywindowview',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='realestateclass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='realestateclass',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='realestatecomplex',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='realestatecomplex',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='realestatecomplexbuilding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='realestatecomplexbuilding',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='realestatecomplexmetroavailability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='realestatecomplexmetroavailability',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='realestatetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='realestatetype',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='transportaccessibilitytype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='transportaccessibilitytype',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='windowview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='windowview',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['apartment_number'], name='property_apartment_num_idx'),
        ),
        migrations.AddIndex(
            model_name='realestatecomplexbuilding',
            index=models.Index(fields=['number'], name='building_number_idx'),
        ),
    ]
