# Generated by Django 6.0.4 on 2026-06-17 05:42

import property.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_alter_apartmentdecoration_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='floor_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='property/floor_plans/', validators=[property.validators.validate_property_image_upload], verbose_name='План этажа'),
        ),
        migrations.AlterField(
            model_name='property',
            name='layout_image',
            field=models.ImageField(blank=True, null=True, upload_to='property/layouts/', validators=[property.validators.validate_property_image_upload], verbose_name='Планировка'),
        ),
        migrations.AlterField(
            model_name='property',
            name='window_view_image',
            field=models.ImageField(blank=True, null=True, upload_to='property/window_views/', validators=[property.validators.validate_property_image_upload], verbose_name='Вид из окна'),
        ),
        migrations.AlterField(
            model_name='realestatecomplex',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='property/complexes/', validators=[property.validators.validate_property_image_upload], verbose_name='Фото ЖК'),
        ),
    ]
