# Generated by Django 6.0.4 on 2026-06-18 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_property_floor_plan_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Группа компаний')),
            ],
            options={
                'verbose_name': 'Группа компаний',
                'verbose_name_plural': 'Группы компаний',
                'db_table': 'company_group',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='developer',
            name='actual_address',
            field=models.TextField(blank=True, null=True, verbose_name='Фактический адрес'),
        ),
        migrations.AddField(
            model_name='developer',
            name='legal_address',
            field=models.TextField(blank=True, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='developer',
            name='primary_state_registration_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='developer',
            name='tax_registration_reason_code',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='developer',
            name='taxpayer_identification_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='developer',
            name='company_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='developers', to='property.companygroup', verbose_name='Группа компаний'),
        ),
    ]
