# Generated by Django 6.0.4 on 2026-06-20 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_alter_city_created_at_alter_city_is_active_and_more'),
        ('property', '0013_companygroup_developer_actual_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть запись.', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_links', to='property.developer', verbose_name='Застройщик')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='developer_links', to='location.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Регион застройщика',
                'verbose_name_plural': 'Регионы застройщиков',
                'db_table': 'developer_region',
                'ordering': ['developer__name', 'region__name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='developer',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='developers', through='property.DeveloperRegion', to='location.region', verbose_name='Регионы'),
        ),
        migrations.AddConstraint(
            model_name='developerregion',
            constraint=models.UniqueConstraint(fields=('developer', 'region'), name='unique_developer_region'),
        ),
    ]
