# Generated by Django 5.2.6 on 2025-09-13 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0001_initial'),
        ('property', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgagecalculation',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property', verbose_name='Объект'),
        ),
        migrations.AlterModelOptions(
            name='mortgagecalculation',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Расчет ипотеки', 'verbose_name_plural': 'Расчеты ипотеки'},
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
