# Generated by Django 5.2.6 on 2025-09-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgagecalculation',
            name='base_property_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Базовая стоимость объекта, руб.'),
            preserve_default=False,
        ),
    ]
