# Generated by Django 6.0.4 on 2026-06-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0002_mortgagecalculation_base_property_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgagecalculation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
