# Generated by Django 6.0.4 on 2026-06-16 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def assign_mortgage_calculation_users(apps, schema_editor):
    """Assign owners to calculations linked to exactly one customer user."""
    mortgage_calculation_model = apps.get_model(
        'mortgage',
        'MortgageCalculation',
    )
    customer_calculation_model = apps.get_model(
        'customer',
        'CustomerCalculation',
    )

    single_owner_calculation_ids = (
        customer_calculation_model.objects
        .values('calculation_id')
        .annotate(user_count=Count('customer__user_id', distinct=True))
        .filter(user_count=1)
        .values_list('calculation_id', flat=True)
    )
    calculation_user_ids = dict(
        customer_calculation_model.objects
        .filter(calculation_id__in=single_owner_calculation_ids)
        .values_list('calculation_id', 'customer__user_id')
        .distinct()
    )
    calculations = []
    for calculation in (
        mortgage_calculation_model.objects
        .filter(pk__in=calculation_user_ids.keys(), user__isnull=True)
        .iterator()
    ):
        calculation.user_id = calculation_user_ids[calculation.pk]
        calculations.append(calculation)

    mortgage_calculation_model.objects.bulk_update(
        calculations,
        ['user'],
        batch_size=500,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_created_at_alter_customer_is_active'),
        ('mortgage', '0003_alter_mortgagecalculation_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgagecalculation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_calculations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.RunPython(
            assign_mortgage_calculation_users,
            migrations.RunPython.noop,
        ),
    ]
